-- QRForge — Supabase schema (optional backend for Dynamic QR / Analytics)
--
-- Run this in the Supabase SQL editor once your project exists.
-- This is OPTIONAL. The static QR generator works 100% without it.
-- Minimal personal data is stored by design.

-- Extensions
create extension if not exists "uuid-ossp";
create extension if not exists "pgcrypto";

-- Users (integrates with Supabase Auth when enabled)
create table if not exists users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  created_at timestamptz not null default now(),
  last_login_at timestamptz
);

-- QR codes (dynamic ones in particular; static ones may also be recorded)
create table if not exists qr_codes (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references users(id) on delete cascade,
  name text not null default 'Untitled',
  qr_type text not null default 'url',
  destination text,                       -- current destination URL
  short_code text unique,                 -- e.g. abc123 -> qrforge.com/abc123
  status text not null default 'active',  -- active | paused | expired
  folder_id uuid references folders(id) on delete set null,
  design jsonb,                           -- colors/logo/margin etc for regenerating the same design
  is_dynamic boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Dynamic destinations (supports scheduled destination changes + history)
create table if not exists qr_destinations (
  id uuid primary key default uuid_generate_v4(),
  qr_id uuid references qr_codes(id) on delete cascade,
  slug text unique not null,
  destination text not null,
  schedule jsonb,                    -- [{ days, startTime, endTime, destination }]
  expire_on timestamptz,
  expire_after_scans integer,
  expire_message text,
  password_hash text,                -- SHA-256 hex (client-side pre-hashed + salted by app layer)
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Scans — minimal analytics (no personal data, coarse region only)
create table if not exists qr_scans (
  id bigint generated by default as identity primary key,
  qr_id uuid references qr_codes(id) on delete cascade,
  device text,
  os text,
  browser text,
  country text,
  region text,
  city text,
  referer text,
  scanned_at timestamptz not null default now()
);
create index if not exists idx_scans_qr_id on qr_scans(qr_id);
create index if not exists idx_scans_scanned_at on qr_scans(scanned_at);

create or replace view scan_metrics as
  select qr_id,
         count(*) as total_scans,
         count(distinct coalesce(device, os, browser)) as unique_scans,
         count(*) filter (where scanned_at >= date_trunc('day', now())) as scans_today,
         count(*) filter (where scanned_at >= date_trunc('week', now())) as scans_week,
         count(*) filter (where scanned_at >= date_trunc('month', now())) as scans_month,
         count(*) filter (where scanned_at >= date_trunc('year', now())) as scans_year
  from qr_scans
  group by qr_id;

-- Campaigns
create table if not exists campaigns (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references users(id) on delete cascade,
  name text not null,
  description text,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table if not exists campaign_items (
  id uuid primary key default uuid_generate_v4(),
  campaign_id uuid references campaigns(id) on delete cascade,
  qr_id uuid references qr_codes(id) on delete cascade,
  label text,
  sort_order integer default 0
);

-- Folders
create table if not exists folders (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

-- Landing pages (hosted under the same domain)
create table if not exists landing_pages (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references users(id) on delete cascade,
  slug text unique not null,
  kind text not null,           -- social | card | menu | product | event | review | whatsapp | payment
  title text,
  config jsonb not null default '{}',
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Templates (seed data / user saved templates)
create table if not exists templates (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references users(id) on delete cascade,  -- null = built-in
  name text not null,
  category text,
  qr_type text,
  fields jsonb,
  design jsonb,
  is_builtin boolean not null default false,
  created_at timestamptz not null default now()
);

-- Brand kits
create table if not exists brand_kits (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references users(id) on delete cascade,
  name text not null default 'My Brand',
  config jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Land (future) — analytics retention policies / subscriptions
create table if not exists analytics_export_jobs (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references users(id) on delete cascade,
  qr_id uuid references qr_codes(id) on delete cascade,
  format text not null,       -- csv | json | pdf
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

-- Simple RLS: users only see their own data.
alter table users enable row level security;
alter table qr_codes enable row level security;
alter table qr_destinations enable row level security;
alter table qr_scans enable row level security;
alter table campaigns enable row level security;
alter table campaign_items enable row level security;
alter table folders enable row level security;
alter table landing_pages enable row level security;
alter table brand_kits enable row level security;

create policy "users_select_own" on users for select using (auth.uid() = id);
create policy "qr_select_own" on qr_codes for select using (auth.uid() = user_id);
create policy "qr_insert_own" on qr_codes for insert with check (auth.uid() = user_id);
create policy "qr_update_own" on qr_codes for update using (auth.uid() = user_id);
create policy "qr_delete_own" on qr_codes for delete using (auth.uid() = user_id);
create policy "dest_select_own" on qr_destinations for select using (auth.uid() = (select user_id from qr_codes where id = qr_id));
create policy "dest_insert_own" on qr_destinations for insert with check (auth.uid() = (select user_id from qr_codes where id = qr_id));
create policy "dest_update_own" on qr_destinations for update using (auth.uid() = (select user_id from qr_codes where id = qr_id));
create policy "scans_select_own" on qr_scans for select using (auth.uid() = (select user_id from qr_codes where id = qr_id));

-- NOTE: the public redirect endpoint (/api/r/:slug) reads qr_destinations and
-- writes qr_scans using the ANON key. For that to work, either:
--   * enable an anon SELECT on qr_destinations joined to qr_codes where status='active',
--     and INSERT on qr_scans (recommended when no user auth), or
--   * set the redirect function to use the service role key (advanced).